### ISSUE TITLE
Not able to merge multiple files?

### ISSUE THREAD

**Issue by itsmevictor** [xilopaint/alfred-pdf-tools#13]
Hi there,

Thank you for building the worfklow. I can't seem to merge more than two files. When I try doing so, I get the "naming" prompt but the new file does not appear anywhere nor appears to have been executed according to the Notifications pane. 

Best,

**Comment by YIPSHINGHIM** [comment]
yea I also have this issue , pls help

**Comment by xilopaint** [comment]
v3 was just released. I think this issue is fixed in the new version so I'm closing the issue. Please, let me know if you face any issue with the new version.
