### ISSUE TITLE
Monterey 12.3, Python Removal not working

### ISSUE THREAD

**Issue by learn2reid** [xilopaint/alfred-pdf-tools#14]
Tried setting path
`export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"` but didnt work. please help

**Comment by xilopaint** [comment]
I'm currently working on a Python 3 version of the workflow. In the meantime you can try installing Python 2 with Homebrew and using the full path of the interpreter on the script field of the workflow objects.

**Comment by xilopaint** [comment]
v3 is released and revamped with Python 3. Any feedback on the new version is appreciated.
