### ISSUE TITLE
Not working on macOS Monterey 12.3.1

### ISSUE THREAD

**Issue by skamal1808** [xilopaint/alfred-pdf-tools#16]
This workflow is not working on Monterey 12.3.1. Please update it as this is an integral part of my daily workflow.

Thanks in advance for helping a technological illiterate person here

**Comment by xilopaint** [comment]
"Not working" if not a helpful bug report. Please, use the issue template.

**Comment by xilopaint** [comment]
I'm closing the issue for now. I will reopen it if you provide further information using the issue template.
