### ISSUE TITLE
This workflow is not working at all in Monterey 12.4

### ISSUE THREAD

**Issue by skamal1808** [xilopaint/alfred-pdf-tools#17]
This workflow is not working at all in the latest public release version of macOS Monterey. When I try to perform any function of this workflow, say- Split by page count or merge of PDF's, absolutely nothing happens. No Output, No notifications, nothing. This is happening with all the function of this workflow

**Comment by xilopaint** [comment]
Why have you opened a new issue? You were advised to use the issue template. The workflow works for me on macOS 12.4 and your reports have no useful information. Edit your original issue using the template if you want to see it analyzed and don't use random and inapplicable labels like you did here.
