### ISSUE TITLE
PDF Tools don't work

### ISSUE THREAD

**Issue by TheRojam** [xilopaint/alfred-pdf-tools#2]
> Given Alfred `v3.1 - Build 718`
> And Alfred PDF Tools `v 1.1.3`
> When I want to `Split`an PDF using Alfred by typing this command into it
> Then no Alfred PDF Tools are shown in the DropDown  

_What am I doing wrong?_  

<img width="594" alt="Using Split in Alfred" src="https://cloud.githubusercontent.com/assets/1362428/18291368/b0b0282e-7487-11e6-800e-4253676a3799.png">
<img width="590" alt="Using Merge in Alfred" src="https://cloud.githubusercontent.com/assets/1362428/18291369/b0b1daa2-7487-11e6-8ccd-9727cb04b858.png">

I hope these Screenshots are useful.

Is there any _information_ is missing?

**Comment by xilopaint** [comment]
Those commands are not keywords, they are file actions. You have to select a file with Alfred and select the appropriate file action.

![screen shot 2016-09-07 at 14 16 19](https://cloud.githubusercontent.com/assets/11052366/18321746/ba12709c-7505-11e6-99f4-52e6c24ad040.png)

**Comment by TheRojam** [comment]
Many thanks for this Hint!

**Comment by GabrieleCalarota** [comment]
I don't understand how to "open a file with alfred"

**Comment by xilopaint** [comment]
> I don't understand how to "open a file with alfred"

You will not open the files. Here's how to perform a [file action](https://www.alfredapp.com/blog/tips-and-tricks/file-actions-from-alfred-or-finder/).
