### ISSUE TITLE
Alfred PDF Tools didn't work for me...

### ISSUE THREAD

**Issue by MartinLau42** [xilopaint/alfred-pdf-tools#26]
**Describe the bug**
I have tried using "Encrypt", "Merge", "Split by Page Count", "Slice in Multiple Files" via Alfred action, but nothing happened. I did understand it utilizes action instead of keywords, and I didn't change anything as well. I have also tried using different PDFs, still nothing happened.

**To reproduce**
I searched the PDF I wanted to apply action to via Alfred file search, then by pressing ^ (i.e. control key) towards the selected PDF to trigger the action, choosing specific actions mentioned above, then press "enter / return" on it, sadly nothing happened. All the workflow actions mentioned above gave the same ERROR message below.

**Debugger information**
ERROR: Alfred PDF Tools[Run Script] Traceback (most recent call last):
  File "alfred_pdf_tools.py", line 125, in <module>
    def optimize(resolution: str, pdf_paths: list[str]) -> None:
TypeError: 'type' object is not subscriptable

**Troubleshooting Information:**
### Workflow version
4.5

### Alfred version
5.1.1

### Python version
3.7.3

### PyCryptodome version
Not Installed

### Rosetta installation status
Not Installed

### macOS version
13.5

### Architecture
i386

**Screenshots**
![error](https://github.com/xilopaint/alfred-pdf-tools/assets/96457184/59614e34-3863-4561-8dcd-cae8dce73d0d)

**Comment by xilopaint** [comment]
You're running the workflow on an old Python version. You can install a newer Python version by running `brew install python` on Terminal.

**Comment by MartinLau42** [comment]
Many thanks for such an amazing workflow you have made! 

After updating the Python to the latest version, I successfully run all the actions but "Optimize" and "Deskew" because of the following error:

![error-of-optimize-and-deskew](https://github.com/xilopaint/alfred-pdf-tools/assets/96457184/8536e7a5-f8cf-46cc-839b-c803f001c700)

![error_continue](https://github.com/xilopaint/alfred-pdf-tools/assets/96457184/1c04b2ba-f1be-4a48-ace5-a37e0d0cd6e7)

**Comment by xilopaint** [comment]
You're running the workflow on an Intel Mac, and those two actions are officially compatible with Apple Silicon only. As a workaround, you can replace the k2pdfopt file with its i386 version (x86), which you can download from [here](https://www.willus.com/k2pdfopt/download/). Each time you update the workflow to a new version, you'll need to do it again.

The i386 architecture can be supported in the future if someone creates a Homebrew formula for k2pdfopt.

**Comment by MartinLau42** [comment]
Fixed! Thank you so much!
