### ISSUE TITLE
How to use this workflow?

### ISSUE THREAD

**Issue by bpPrg** [xilopaint/alfred-pdf-tools#6]
It seems like to be very useful alfred workflow. However, I can not find it working.

I tried hitting keywords like "optimize", "encrypt", "merge" etc in alfred, alfred shows other files
and options but not this workflow options.

My question is how to use this workflow?

Attempt:
selected a pdf file in finder.
opened alfred
typed split, I did not get split command from this workflow

**Comment by xilopaint** [comment]
I'm closing the issue. If you still have any question regarding the workflow operation, please, just ask it here.
