### ISSUE TITLE
Merging pdf files.

### ISSUE THREAD

**Issue by rp2ppu-zz** [xilopaint/alfred-pdf-tools#7]
Work flow not working when pdf files selected form different paths.
"Can't merge pdf files from different paths."

**Comment by xilopaint** [comment]
The workflow is designed to not allow merging files from multiple paths. It's possible to exclude this exception but we would still have a problem of defining the appropriate location for the output PDF file. What do you think?

**Comment by xilopaint** [comment]
I'm closing the issue. If you still interested just comment and I can reopen.

**Comment by rp2ppu** [comment]
Sure. Thank you.
